# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 22:24
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consignee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignee_name', models.CharField(max_length=150)),
                ('consignee_street', models.CharField(max_length=True)),
                ('consignee_state', models.CharField(max_length=2)),
                ('consignee_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_number', models.IntegerField()),
                ('carrier', models.CharField(max_length=True)),
                ('pickup_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('shipper', models.CharField(max_length=True)),
                ('consignee', models.CharField(max_length=True)),
                ('po_number', models.CharField(max_length=True)),
                ('pu_number', models.CharField(max_length=True)),
                ('pieces', models.IntegerField()),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipper_name', models.CharField(max_length=150)),
                ('shipper_street', models.CharField(max_length=True)),
                ('shipper_state', models.CharField(max_length=2)),
                ('shipper_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
            ],
        ),
    ]
