# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_number', models.IntegerField()),
                ('carrier', models.CharField(max_length=True)),
                ('pickup_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('shipper', models.CharField(max_length=True)),
                ('consignee', models.CharField(max_length=True)),
                ('po_number', models.CharField(max_length=True)),
                ('pu_number', models.CharField(max_length=True)),
                ('pieces', models.IntegerField()),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
